micronaut:
  server:
    port: ${MICRONAUT_SERVER_PORT:8080}
  application:
    name: keymanagerRest

#Métricas expostas ao micrometer/prometheus
  metrics:
    enabled: true
    export:
      prometheus:
        enabled: true
        descriptions: true
        step: PT1M

#Swagger pra dar aquela força na documentação
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**

#Jaeger para fazer o tracing da aplicação
tracing:
  jaeger:
    enabled: true
    sampler:
      probability: 0.1

# Liberar o Endpoint de Health da aplicação, equivalente ao Actuator
endpoints:
  health:
    enabled: true
    sensitive: false
    details-visible: ANONYMOUS

grpc:
  client:
    plaintext: true
    max-retry-attempts: 10
  channels:
    keyManager:
      address: ${KEY_MANAGER_HOST:localhost}:${KEY_MANAGER_PORT:50051}

##
# Jackson configuration
# https://github.com/micronaut-projects/micronaut-core/issues/240
# https://geowarin.com/correctly-handle-jsr-310-java-8-dates-with-jackson/
# https://www.baeldung.com/jackson-serialize-dates
##
jackson:
  serialization:
    writeDatesAsTimestamps: false